language: python
python:
  - "3.4"

env:
  global:
    - TRAVIS_TAG="$(date -u '+%Z-%y%m%d-%H%M')"

branches:
  only:
    - "1.0"

script:
  - python check.py

before_deploy:
  - zip -r -9 SChinese.zip "." -x "./.git/*" "./check.py" "./.travis.yml" "./output.log"
  - export RBody=$(cat ./output.log)
  - git config --local user.name "$user_name"
  - git config --local user.email "$user_email"
  - git tag "$TRAVIS_TAG"

deploy:
  provider: releases
  api_key: $gh_token
  prerelease: true
  draft: false
  body: $RBody
  file: "SChinese.zip"
  skip_cleanup: true
  on:
    branch: "1.0"